---
- name: configure web server with tls
  hosts: nodes
  gather_facts: true
  become: true
  vars:
    no_tls_port: 80
    tls_port: 443
    cert_dir_path: /etc/ssl
    keys_dir_path: /etc/ssl/private
  tasks:
    - name: install epel-release for repos with python2-pip
      yum:
        name:
          - epel-release
        state: present

    - name: instal pip
      yum:
        name:
          - python2-pip
    
    - name: upgrade pip
      pip:
        name: pip==20.3.4

    - name: install python dependencies
      pip:
        name: cryptography>=1.2.3

    - name: create nginx repo definition
      copy:
        src: nginx.repo
        dest: /etc/yum.repos.d/nginx.repo
        owner: root
        group: root
        mode: 0644

    - name: install nginx
      yum:
        name: nginx
        update_cache: true
        state: present

    - name: create certificates directory
      file: 
        path: "{{ cert_dir_path }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: create keys directory
      file: 
        path: "{{ keys_dir_path }}"
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: create private key
      community.crypto.openssl_privatekey:
        path: "{{ keys_dir_path }}/ansible.key"

    - name: create simple self-signed certificate
      community.crypto.x509_certificate:
        path: "{{ cert_dir_path }}/ansible.pem"
        privatekey_path: "{{ keys_dir_path }}/ansible.key"
        provider: selfsigned

    - name: copy main nginx config file
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - name: copy site's nginx config file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - name: ensure nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: true

    - name: insert firewalld rule for nginx no tls
      firewalld:
        port: "{{ no_tls_port }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      ignore_errors: true
    
    - name: insert firewalld rule for nginx tls
      firewalld:
        port: "{{ tls_port }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      ignore_errors: true

    
  post_tasks:
    - name: check web site from control server by http protocol
      uri:
        url: "http://{{ ansible_host }}:{{ no_tls_port }}"
        return_content: true
      connection: local
      register: example_webpage_out
      failed_when: example_webpage_out.status != 200

    - name: check web site from control server by https protocol
      uri:
        url: "https://{{ ansible_host }}:{{ tls_port }}"
        validate_certs: false
        return_content: true
      connection: local
      register: example_webpage_out
      failed_when: example_webpage_out.status != 200

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
